# NORMAL GET CALLS QUERY - schema
'''
{
    allCakes{
        id
        name
        price
        flavor{
            id
            name
        }
    }
}
'''
'''
{
  allCakes{
    name
    flavor{
      name
    }
  }
}'''

'''
{
  flavorByName(name:""){
    id
    name
  }
}
'''

'''
cake by flavor name
{
  flavorByName(name:"Vanilla"){
    id
    name
    cakeSet{
      name
    }
  }
}

{
  flavorByName(name:"Chocolate"){
    id
    name
    cakeSet{
      id
      name
    }
  }
}

{
  flavorByName(name: "Chocolate") {
    id
    name
    cakeSet {
      id
      name
      price
    }
  }
}

'''

# FIlTER QUERIES GET CALLS - schema1

'''
{
  allCakes{
    edges{
      node{
        id
        name
      }
    }
  }
}
'''

'''
{
  allFlavors{
    edges{
      node{
        id
        name
      }
    }
  }
}
'''
'''
filter by ID generated by graphql
{
  flavor(id: "Rmxhdm9yTm9kZTox"){
    name
  }
}

{
  flavor(id: "Rmxhdm9yTm9kZTox"){
    id
    name
  }
}

{
  cake(id:"Q2FrZU5vZGU6Mg=="){
    id
    name
    price
  }
}

{
  cake(id:"Q2FrZU5vZGU6Mg=="){
    id
    name
  }
}
'''

'''
cake and respective flavors
{
  allCakes{
    edges
    {
      node{
        id
        name
        flavor{
          id
          name
        }
      }
    }
  }
}
'''
'''
flavors and respective cakes
{
  allFlavors{
    edges{
      node{
        id
        name
        cakeSet{
          edges{
            node{
              id
              name
              isDecorated
              price
            }
          }
        }
      }
    }
  }
}
'''
'''
icontains
{
  allCakes(name_Icontains: "ee"){
    edges{
      node{
        name,
        price
      }
    }
  }
}

startswith
{
  allCakes(name_Istartswith: "b"){
    edges{
      node{
        name,
        price
      }
    }
  }
}
'''

'''
related fields filter
{
  allCakes(flavor_Name: "Vanilla"){
    edges{
      node{
        name,
        price
      }
    }
  }
}
'''

# pagination queries

"""
To visit next page
{
  cakes(first: 2, after: "YXJyYXljb25uZWN0aW9uOjI=") {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
      node {
        id
        name
        price
      }
    }
  }
}
"""

"""
To visit previous page
{
  cakes(first: 2, before: "YXJyYXljb25uZWN0aW9uOjI=") {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
      node {
        id
        name
        price
      }
    }
  }
}

"""
"""
First time fetching
{
  cakes(first: 2) {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
      node {
        id
        name
        price
      }
    }
  }
}

"""
