# Generated by Django 3.2.9 on 2021-11-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_decorated', models.BooleanField(default=False)),
                ('price', models.FloatField(default=5.0)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cakeshop.flavor')),
            ],
        ),
    ]
